-- Seed del catalogo GLOBAL de especialidades medicas (empresa_id null),
-- para que las clinicas no tengan que crear desde cero las
-- especialidades mas comunes reconocidas internacionalmente. Idempotente
-- via "on conflict" contra el indice unico parcial de la migracion 044
-- (uq_especialidades_global_nombre).
insert into especialidades (nombre, empresa_id, activo) values
  ('Medicina General', null, true),
  ('Medicina Familiar', null, true),
  ('Medicina Interna', null, true),
  ('Pediatria', null, true),
  ('Neonatologia', null, true),
  ('Geriatria', null, true),
  ('Ginecologia y Obstetricia', null, true),
  ('Medicina Materno Fetal', null, true),
  ('Infertilidad y Medicina Reproductiva', null, true),
  ('Cirugia General', null, true),
  ('Cirugia Pediatrica', null, true),
  ('Cirugia Plastica y Reconstructiva', null, true),
  ('Cirugia Cardiovascular', null, true),
  ('Cirugia Toracica', null, true),
  ('Cirugia Vascular', null, true),
  ('Cirugia Oncologica', null, true),
  ('Cirugia de Trasplantes', null, true),
  ('Cirugia Bariatrica', null, true),
  ('Cirugia de Mano', null, true),
  ('Cirugia Maxilofacial', null, true),
  ('Coloproctologia', null, true),
  ('Neurocirugia', null, true),
  ('Cardiologia', null, true),
  ('Cardiologia Pediatrica', null, true),
  ('Angiologia', null, true),
  ('Neumologia', null, true),
  ('Gastroenterologia', null, true),
  ('Hepatologia', null, true),
  ('Nefrologia', null, true),
  ('Urologia', null, true),
  ('Urologia Pediatrica', null, true),
  ('Andrologia', null, true),
  ('Endocrinologia', null, true),
  ('Endocrinologia Pediatrica', null, true),
  ('Hematologia', null, true),
  ('Oncologia Medica', null, true),
  ('Oncologia Radioterapica', null, true),
  ('Reumatologia', null, true),
  ('Infectologia', null, true),
  ('Alergologia e Inmunologia', null, true),
  ('Neurologia', null, true),
  ('Neurologia Pediatrica', null, true),
  ('Psiquiatria', null, true),
  ('Psiquiatria Infantil y de la Adolescencia', null, true),
  ('Psicologia Clinica', null, true),
  ('Dermatologia', null, true),
  ('Dermatologia Pediatrica', null, true),
  ('Oftalmologia', null, true),
  ('Otorrinolaringologia', null, true),
  ('Foniatria', null, true),
  ('Fonoaudiologia y Terapia del Lenguaje', null, true),
  ('Ortopedia y Traumatologia', null, true),
  ('Ortopedia Pediatrica', null, true),
  ('Medicina Fisica y Rehabilitacion', null, true),
  ('Fisioterapia', null, true),
  ('Terapia Ocupacional', null, true),
  ('Anestesiologia', null, true),
  ('Medicina del Dolor', null, true),
  ('Radiologia e Imagenologia', null, true),
  ('Radiologia Intervencionista', null, true),
  ('Medicina Nuclear', null, true),
  ('Patologia y Anatomia Patologica', null, true),
  ('Medicina de Emergencias', null, true),
  ('Medicina Critica y Cuidados Intensivos', null, true),
  ('Medicina Critica Pediatrica', null, true),
  ('Medicina del Deporte', null, true),
  ('Medicina Ocupacional y Laboral', null, true),
  ('Medicina Legal y Forense', null, true),
  ('Genetica Medica', null, true),
  ('Nutricion y Dietetica', null, true),
  ('Toxicologia', null, true),
  ('Salud Publica y Medicina Preventiva', null, true),
  ('Epidemiologia', null, true),
  ('Odontologia General', null, true),
  ('Ortodoncia', null, true),
  ('Endodoncia', null, true),
  ('Periodoncia', null, true),
  ('Prostodoncia', null, true),
  ('Odontopediatria', null, true),
  ('Cirugia Oral y Maxilofacial', null, true)
on conflict (nombre) where empresa_id is null do nothing;
